### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by mjrdnk** [vickychijwani/quickwiki#14]
Info website with simple info functionality and tiny api

**Comment by vickychijwani** [comment]
@mjrdnk could you explain in more detail what the exact issue here is?

**Comment by mjrdnk** [comment]
It's actually no issue, but only an idea. It might be the wrong place to post it, but I was thinking to create a simple website with info about the idea, alongside github and chrome store. Let me know if you like the idea and if it is really needed. I am also open to contributed in any other way. Best Regards!

**Comment by vickychijwani** [comment]
I think that between Github and the Chrome webstore, it's probably enough since this is a small extension and I don't plan to add many more features in the future.

But I'm open to hearing suggestions. For example, if you have feature ideas and pull requests that you would like to contribute. Then it might also make sense to have a small website.

**Comment by moltra** [comment]
I can create a small wordpress website on my existing Azure webserver.

**Comment by vickychijwani** [comment]
Hi @moltra! Thanks for offering to host the website, but like I said, this extension and the user base is small enough that it doesn't justify having a separate website for it (not to mention domain costs). I genuinely appreciate the thought though.
